name: Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test-utils:
  runs-on: ubuntu-latest
  steps:
    - name: clone repo and checkout main
      uses: actions/checkout@v4
    - name: install dependencies
      run: npm install
    - name: run utils tests
      run: npm test utils.test
